apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: slack-bot
  namespace: flux-system
spec:
  type: slack
  channel: C09LA6EML5A # k8s-notification
  address: https://slack.com/api/chat.postMessage
  secretRef:
    name: slack-bot-token
