apiVersion: v1
kind: Secret
metadata:
  namespace: flux-system
  name: slack-bot-token
type: Opaque
data:
  token: ENC[AES256_GCM,data:V41cOboRohkbYk5422pUxAD/pvrxGsCr1uAtkW9HwujJjenoeSWj6SiqIHFAqW7kZqXQyf/KUzWmTHnAR9wGywl9KewkX3cOXpgjyA==,iv:lGnAowpGLX8zMpEYLxQRlejYXea9KPnaxTyg7W2eQpE=,tag:DrmUC68i5GbRGpnQuAWDlA==,type:str]
sops:
  gcp_kms:
    - resource_id: projects/shinji-nishioka-test/locations/asia-northeast2/keyRings/sops/cryptoKeys/sops-key
      created_at: "2025-10-13T22:32:17Z"
      enc: CiQAwpuH8l91/joYQblsQz9ptOHchERg6V5IuiQv52H/YJkzGKESSQC49uDoBjcQ+LnWOkLD7Ej2uhkUuYPYfVzsSud2XkTAVnESLOmr+2lFbLY1kEjWcxGwlTB06DGk3Vo6HnSidwcju9D9nhE21XA=
  lastmodified: "2025-10-13T22:32:17Z"
  mac: ENC[AES256_GCM,data:BTeIybblHny2kxPKxSljHbyjjktl50xuwU7l0lHGOtbqJpz5WXJrWODobQqXQGmSMHrCWQrw9uLv2hudeybBAHQeuEj/0A+E4vaR2ya/uodC5Bcc1LLeMg9EUrVdTuiLlbtmoaKdFdkvdcnRF5U4hTTzisqrD6sSV6q5wHxNyow=,iv:yxkTmLh2v6sj3ZKHvTxcIbMdsIBhjuM4ODn/P5rYkYw=,tag:XfA5xZGVznh3cZJT755kQg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
