apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: goldilocks
spec:
  interval: 30m
  chart:
    spec:
      chart: goldilocks
      version: "10.1.0"
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable
  values:
    controller:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      resources:
        requests:
          cpu: 250m
          memory: 500Mi
        limits:
          cpu: 250m
          memory: 500Mi
    dashboard:
      replicaCount: 1
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      resources:
        requests:
          cpu: 250m
          memory: 500Mi
        limits:
          cpu: 250m
          memory: 500Mi
