apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: zalando
spec:
  interval: 30m
  chart:
    spec:
      chart: postgres-operator
      version: "1.14.0"
      sourceRef:
        kind: HelmRepository
        name: postgres-operator-charts
  values:
    resources:
      requests:
        cpu: 1m
        memory: 41M
      limits:
        cpu: 3m
        memory: 61M
