apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: zalando
spec:
  interval: 30m
  chart:
    spec:
      chart: postgres-operator
      version: "1.14.0"
      sourceRef:
        kind: HelmRepository
        name: postgres-operator-charts
  values:
    configKubernetes:
      enable_pod_antiaffinity: true
      pod_antiaffinity_preferred_during_scheduling: true
      pod_antiaffinity_topology_key: "topology.kubernetes.io/zone"
      spilo_fsgroup: "103"
    nodeSelector:
      cloud.google.com/gke-spot: "true"
    resources:
      requests:
        cpu: 250m
        memory: 500Mi
      limits:
        cpu: 250m
        memory: 500Mi
