apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: postgresql
  values:
    global:
      postgresql:
        auth:
          existingSecret: "postgresql-secret"
    primary:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
    readReplicas:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
