apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external-https-gateway
  namespace: gateway-infra
  annotations:
    networking.gke.io/certmap: nishiokatest-cert-map
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    allowedRoutes:
      namespaces:
        from: atlantis
  addresses:
    - type: NamedAddress
      value: nishiokatest-ip
