apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external-https-gateway
  namespace: gateway-infra
  annotations:
    # Gatewayに紐付けるGCP Certificate Managerの証明書マップを指定。
    # この証明書マップはTerraformで作成されています (see: terraform/gcp/02-network/certificate_manager.tf)。
    networking.gke.io/certmap: nishiokatest-cert-map
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            shared-gateway-access: "true"
  addresses:
    - type: NamedAddress
      # Gatewayに紐付けるGCPの静的IPアドレス名を指定。
      # この静的IPアドレスはTerraformで作成されています (see: terraform/gcp/02-network/dns.tf)。
      value: nishiokatest-ip
