apiVersion: v1
kind: Secret
metadata:
  namespace: atlantis
  name: cloudflare-secret
type: Opaque
data:
  cloudflare_api_token: ENC[AES256_GCM,data:z27Oz88Hf74kDHSpOiZh7HC92ULniN5kzKh3Gk9fhIQPdifsvNU1eKw5okW3FRTFc0jD7MiHxmk=,iv:u2+dabfvUsJEm05XZ7h7H8Dh0Eec+sKI3H1J0C40A0Q=,tag:2KlHE06IF4hXS/jlw/JDaw==,type:str]
sops:
  gcp_kms:
    - resource_id: projects/shinji-nishioka-test/locations/asia-northeast2/keyRings/sops/cryptoKeys/sops-key
      created_at: "2026-03-07T05:38:21Z"
      enc: CiQAwpuH8vDvP00Ll6E6PbNNUGO9MFORwOCkSPQ7RvFIeQs02EkSSQC49uDon7gfEJycef9URT170PvzTBJui+LK0wfA2GRQ7qlq59aEcTs9ovoDokVzbBfgqfDgBNuYLp05+mTspVb3VRI4yG/aEho=
  lastmodified: "2026-03-07T05:38:21Z"
  mac: ENC[AES256_GCM,data:LgJAzpcylASDTZ17UShvkz0tuXKUVXgliGVCMwigBsBZpOHsLT3OHwe6gfbZ188bXeY45mqKxanXQ+yq5Y30XgomCxnsdbjGeqHlNxb/6kQsezLhow700H5lEBVXm86er62JvjWKGRhfus1C2mpwGD11zlICxJxL3qfxCVRAI80=,iv:fKAKUwDZSZ4gSZoKoCGkrmvxALhBGAH/PBAg2aGkuL0=,tag:G/4Mtl7i480glMAi3pqQZg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
