apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: oauth2-proxy-healthcheck
  namespace: oauth2-proxy
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 4180
        requestPath: /ping
  targetRef:
    group: ""
    kind: Service
    name: oauth2-proxy