apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 30m
  chart:
    spec:
      chart: oauth2-proxy
      version: "8.2.1"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
  values:
    ingress:
      enabled: false
    authenticatedEmailsFile:
      enabled: true
      restricted_access: |-
        s61nov11.shinji.nishioka@gmail.com
    config:
      existingSecret: oauth2-proxy-google-secret
      configFile: |-
        upstreams = [ "http://atlantis.atlantis.svc.cluster.local" ]
        provider = "google"
        skip_auth_routes = "POST=^/events$"
    nodeSelector:
      cloud.google.com/gke-spot: "true"
    resources:
      requests:
        cpu: 250m
        memory: 500Mi
      limits:
        cpu: 250m
        memory: 500Mi
# Adding resources