creation_rules:
  - path_regex: .*.yaml$
    encrypted_regex: ^(data|stringData)$
    # SOPSでファイルを暗号化するために使用するGCP KMSキーを指定。
    # このKMSキーはTerraformで作成されています (see: terraform/gcp/kms/kms.tf)。
    gcp_kms: projects/shinji-nishioka-test/locations/asia-northeast2/keyRings/sops/cryptoKeys/sops-key
