apiVersion: v1
kind: Secret
metadata:
    namespace: goldilocks
    name: google-secret
type: Opaque
data:
    cookie-secret: ENC[AES256_GCM,data:NE+yzQKCLGz9I4Br7t8OBjg/APxXmQnP9fdxqo0fMGf0KelFo9BnEFtwGTM=,iv:LESceI0XKiQsWgyopAKAtWsY4KTfmhci8FYF6rvrEQ4=,tag:qCJdNOM13WjmZoZdlc/tbQ==,type:str]
    client-secret: ENC[AES256_GCM,data:SzXnkKQ8q2mdVJoguVrD3VjkkvjHO3TfVu+plZvkWXuRn6psbN7zyHzYUEvghmTT,iv:17Ijn3v0KdOO+u5E2tD7hW1JW4ih+bB3mcHHN9iFijs=,tag:1PPXS86IjPYEtA46Rex2aw==,type:str]
    client-id: ENC[AES256_GCM,data:wHrqjd8c0sBsfcZGw7EwB0BgNtz9H6Arb7utnyzPuYSCN1zx8X0KGx1txMdh22Cz4HIwW96O8ivH7mV2Y3TguPPd0HDxswr+PktoxBt/9a++UPi++CU5z+gD+Mhyx7ZG,iv:cpaL0b56oPzH3cFK3AKbbyH37FOilIdEo5FReFmUvzY=,tag:n2hgqV26bUsjHBsMjFa/Cw==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/shinji-nishioka-test/locations/asia-northeast2/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-10-05T14:01:29Z"
          enc: CiQAwpuH8hwli0u3A8N0Qfndo+upda63KnnBYD3lboiU0grNstgSSQC49uDo6h4wouInLwr8ySTVf7nsTpg9T/j5N+DVP6mlcVB6QU2EeWuXB08vP3jyciGCsQWLjLAyTPSFc4MnLk2i9eC98qUkcaU=
    lastmodified: "2025-10-05T14:01:29Z"
    mac: ENC[AES256_GCM,data:Gl6eMJHETe6UpCTIAfkdayU6rRqu8f85dAh3bRufR4znWq6kCEfpmSA2OFwCap6wBORpBZs1eZI/AB1RlaCR8HTZAaPyEGSLByK/JkvoYC55/Pi5wpNwAWBtvO88kYLIR+RKP/kPlZQ3e3IQq0bmecNBgQbknZoKNa0RPMe0coI=,iv:4GbTOpskE1Icvrp2zYfzM3ES5sK6E1myh0DhvpoecfE=,tag:jAJGAlNaQzoijjhOzz/KVQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
