apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: digger-cluster
  namespace: digger
spec:
  teamId: "digger"
  volume:
    size: 1Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cloud.google.com/gke-spot
            operator: In
            values:
            - "true"
  numberOfInstances: 1
  users:
    zalando:  # database owner
    - superuser
    - createdb
  postgresql:
    version: "17"
  resources:
    requests:
      cpu: 250m
      memory: 500Mi
    limits:
      cpu: 250m
      memory: 500Mi