apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: digger-cluster
  namespace: digger
spec:
  teamId: "digger"
  allow_dirty: true
  volume:
    size: 1Gi
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cloud.google.com/gke-spot
          operator: In
          values:
          - "true"
  numberOfInstances: 1
  users:
    digger:  # database owner
    - superuser
    - createdb
  databases:
    digger: digger
  postgresql:
    version: "17"
  resources:
    requests:
      cpu: 250m
      memory: 500Mi
    limits:
      cpu: 250m
      memory: 500Mi