apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: digger-cluster
  namespace: digger
spec:
  teamId: "digger"
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    digger:  # database owner
    - superuser
    - createdb
  databases:
    digger: digger
  postgresql:
    version: "17"
  resources:
    requests:
      cpu: 4m
      memory: 107M
    limits:
      cpu: 9m
      memory: 169M