apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: "1.18.0"
      sourceRef:
        kind: HelmRepository
        name: harbor
  values:
    externalURL: https://harbor.nishiokatest.xyz
    expose:
      type: clusterIP
      tls:
        enabled: false
    existingSecretAdminPassword: harbor-secret
    core:
      resources:
        requests:
          cpu: 1m
          memory: 56M
        limits:
          cpu: 3m
          memory: 70M
    database:
      internal:
        resources:
          requests:
            cpu: 15m
            memory: 79M
          limits:
            cpu: 20m
            memory: 99M
    jobservice:
      resources:
        requests:
          cpu: 2m
          memory: 17M
        limits:
          cpu: 4m
          memory: 21M
    nginx:
      resources:
        requests:
          cpu: 1m
          memory: 6292k
        limits:
          cpu: 2m
          memory: 7341k
    portal:
      resources:
        requests:
          cpu: 1m
          memory: 4195k
        limits:
          cpu: 2m
          memory: 5243k
    redis:
      internal:
        resources:
          requests:
            cpu: 3m
            memory: 6292k
          limits:
            cpu: 5m
            memory: 8389k
    registry:
      registry:
        resources:
          requests:
            cpu: 1m
            memory: 7341k
          limits:
            cpu: 2m
            memory: 12M
      controller:
        resources:
          requests:
            cpu: 1m
            memory: 12M
          limits:
            cpu: 2m
            memory: 14M
    trivy:
      resources:
        requests:
          cpu: 1m
          memory: 5243k
        limits:
          cpu: 2m
          memory: 8389k