apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: "1.18.0"
      sourceRef:
        kind: HelmRepository
        name: harbor
  values:
    externalURL: https://harbor.nishiokatest.xyz
    expose:
      type: clusterIP
      tls:
        enabled: false
    existingSecretAdminPassword: harbor-secret
    core:
      resources:
        requests:
          cpu: 1m
          memory: 77M
        limits:
          cpu: 3m
          memory: 90M
    database:
      internal:
        resources:
          requests:
            cpu: 15m
            memory: 79M
          limits:
            cpu: 20m
            memory: 114M
    jobservice:
      resources:
        requests:
          cpu: 3m
          memory: 32M
        limits:
          cpu: 5m
          memory: 37M
    nginx:
      resources:
        requests:
          cpu: 1m
          memory: 11M
        limits:
          cpu: 2m
          memory: 13M
    portal:
      resources:
        requests:
          cpu: 1m
          memory: 8389k
        limits:
          cpu: 1m
          memory: 14M
    redis:
      internal:
        resources:
          requests:
            cpu: 4m
            memory: 8389k
          limits:
            cpu: 5m
            memory: 11M
    registry:
      registry:
        resources:
          requests:
            cpu: 1m
            memory: 15M
          limits:
            cpu: 2m
            memory: 20M
      controller:
        resources:
          requests:
            cpu: 1m
            memory: 21M
          limits:
            cpu: 2m
            memory: 25M
    trivy:
      resources:
        requests:
          cpu: 1m
          memory: 11M
        limits:
          cpu: 2m
          memory: 142M