apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: "1.18.0"
      sourceRef:
        kind: HelmRepository
        name: harbor
  values:
    externalURL: https://harbor.nishiokatest.xyz
    expose:
      type: clusterIP
      tls:
        enabled: false
    existingSecretAdminPassword: harbor-secret
    core:
      resources:
        requests:
          cpu: 1m
          memory: 69M
        limits:
          cpu: 3m
          memory: 78M
    database:
      internal:
        resources:
          # Goldilocks推奨値の2倍を設定
          requests:
            cpu: 30m
            memory: 170M
          limits:
            cpu: 30m
            memory: 170M
    jobservice:
      resources:
        requests:
          cpu: 2m
          memory: 21M
        limits:
          cpu: 3m
          memory: 25M
    nginx:
      resources:
        requests:
          cpu: 1m
          memory: 9438k
        limits:
          cpu: 2m
          memory: 141M
    portal:
      resources:
        requests:
          cpu: 1m
          memory: 4195k
        limits:
          cpu: 2m
          memory: 4195k
    redis:
      internal:
        resources:
          requests:
            cpu: 4m
            memory: 7341k
          limits:
            cpu: 5m
            memory: 8389k
    registry:
      registry:
        resources:
          # Goldilocks推奨値の8倍を設定
          requests:
            cpu: 8m
            memory: 96M
          limits:
            cpu: 16m
            memory: 112M
      controller:
        resources:
          requests:
            cpu: 1m
            memory: 12M
          limits:
            cpu: 2m
            memory: 13M
    trivy:
      resources:
        requests:
          cpu: 1m
          memory: 5243k
        limits:
          cpu: 2m
          memory: 7341k