apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: "1.18.0"
      sourceRef:
        kind: HelmRepository
        name: harbor
  values:
    externalURL: https://harbor.nishiokatest.xyz
    expose:
      type: clusterIP
      tls:
        enabled: false
    existingSecretAdminPassword: harbor-secret
    core:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      resources:
        requests:
          cpu: 250m
          memory: 500Mi
        limits:
          cpu: 250m
          memory: 500Mi
    database:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      resources:
        requests:
          cpu: 250m
          memory: 500Mi
        limits:
          cpu: 250m
          memory: 500Mi
    jobservice:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      resources:
        requests:
          cpu: 250m
          memory: 500Mi
        limits:
          cpu: 250m
          memory: 500Mi
    nginx:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      resources:
        requests:
          cpu: 250m
          memory: 500Mi
        limits:
          cpu: 250m
          memory: 500Mi
    portal:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      resources:
        requests:
          cpu: 250m
          memory: 500Mi
        limits:
          cpu: 250m
          memory: 500Mi
    redis:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      resources:
        requests:
          cpu: 250m
          memory: 500Mi
        limits:
          cpu: 250m
          memory: 500Mi
    registry:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      registry:
        resources:
          requests:
            cpu: 250m
            memory: 500Mi
          limits:
            cpu: 250m
            memory: 500Mi
      controller:
        resources:
          requests:
            cpu: 250m
            memory: 500Mi
          limits:
            cpu: 250m
            memory: 500Mi
    trivy:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      resources:
        requests:
          cpu: 250m
          memory: 500Mi
        limits:
          cpu: 250m
          memory: 500Mi