apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: "1.18.0"
      sourceRef:
        kind: HelmRepository
        name: harbor
  values:
    expose:
      type: clusterIP
      tls:
        enabled: false
    core:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
    database:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
    jobservice:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
    nginx:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
    portal:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
    redis:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
    registry:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
    trivy:
      nodeSelector:
        cloud.google.com/gke-spot: "true"