apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: harbor
  namespace: harbor
spec:
  parentRefs:
  - name: external-https-gateway
    namespace: gateway-infra
  hostnames:
  - "harbor.nishiokatest.xyz"
  rules:
  - backendRefs:
    - name: harbor
      port: 80
